"use client";

import { useRef } from "react";
import { motion, useScroll, useTransform, useMotionTemplate, useSpring } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import { Search, ShoppingBag, Bookmark, User } from "lucide-react";
import { useCartStore } from "@/lib/store";

// The true transparent cutouts correctly generated by our AI script!
const models = [
  { id: 1, src: "/1_trans.png", title: "Avant-Garde Spring", price: "$1,295", desc: "Sleek minimalist dress featuring an asymmetrical cut. Perfect for high-fashion spring edits." },
  { id: 2, src: "/2_trans.png", title: "Urban Silhouette", price: "$895", desc: "Utility-inspired avant-garde streetwear. Heavy-duty straps and oversized pockets." },
  { id: 3, src: "/3_trans.png", title: "Minimalist Edit", price: "$1,050", desc: "Sharp, oversized tailored suit with broad shoulders and a crisp white undershirt." },
  { id: 4, src: "/4_trans.png", title: "Evening Collection", price: "$2,100", desc: "A dramatically long velvet evening dress with a deep slit and elegant styling." },
  { id: 5, src: "/5_trans.png", title: "Crimson Flow", price: "$1,850", desc: "A sweeping crimson red dress optimized for profound studio silhouettes and dramatic movement." },
  { id: 6, src: "/6_trans.png", title: "Textured Wool", price: "$1,450", desc: "Heavy oversized textured wool coat paired with wide-leg trousers for a bold structural statement." },
  { id: 7, src: "/7_trans.png", title: "Metallic Orbit", price: "$2,600", desc: "Striking metallic silver outfit constructed for futuristic, sharp aesthetics and deep reflections." },
  { id: 8, src: "/8_trans.png", title: "Noir Leather", price: "$3,100", desc: "Sleek tailored black leather trench coat. The pinnacle of moody, intense evening wear." },
];

export default function Home() {
  const containerRef = useRef(null);
  const { items, openCart, wishlistItems } = useCartStore();

  // Track the scroll of the whole page, seamlessly tying the giant models to the right sidebar
  const { scrollYProgress } = useScroll();
  
  // Wrap the rigid scroll value in a physics spring to create buttery-smooth inertia
  const smoothProgress = useSpring(scrollYProgress, {
    stiffness: 450,
    damping: 40,
    mass: 0.6,
    restDelta: 0.001
  });

  // Create a looped set for infinite scrolling feel
  const loopedModels = [...models, ...models, ...models];

  return (
    <main ref={containerRef} className="bg-[#f9f9fa] text-black font-sans relative">
      <nav className="fixed top-0 w-full z-50 bg-[#f9f9fa]/90 backdrop-blur-md border-b border-black/5">
        <div className="flex items-center justify-between px-8 py-6">
          <h1 className="text-xl font-bold tracking-widest uppercase">COLIN GUEST</h1>
          <div className="hidden md:flex gap-12 text-[10px] tracking-[0.2em] uppercase font-bold">
            <button className="hover:text-black/60 transition-colors">Runway</button>
            <button className="text-black border-b border-black pb-1">The Lookbook</button>
            <Link href="/collections" className="hover:text-black/60 transition-colors">Collections</Link>
          </div>
          <div className="flex items-center gap-6 text-xs font-semibold tracking-widest uppercase">
            <Search size={18} />
            <Link href="/login" className="cursor-pointer hover:scale-110 transition-transform block">
              <User size={18} strokeWidth={1.5} />
            </Link>
            <Link href="/wishlist" className="cursor-pointer hover:scale-110 transition-transform block">
              <Bookmark size={18} strokeWidth={1.5} />
            </Link>
            <div className="flex items-center gap-2 cursor-pointer hover:text-black/60 transition-colors" onClick={openCart}>
              <ShoppingBag size={18} />
              <span>Cart ({items.length})</span>
            </div>
          </div>
        </div>
      </nav>

      <div className="flex w-full pt-20 relative">
        {/* LEFT/CENTER: Sticky 3D Carousel (Expanded to fill the whole left space without text!) */}
        <div className="w-[65%] lg:w-[70%] sticky top-20 h-[calc(100vh-5rem)] flex items-center justify-center z-10 perspective-[1200px] overflow-hidden">
          
          <div className="absolute top-[20%] z-0 text-center w-full pointer-events-none opacity-[0.03]">
            <h2 className="text-[6rem] md:text-[10rem] font-serif tracking-tighter leading-none">
              SPRING 25
            </h2>
          </div>

          <div className="relative w-full h-[85%] flex items-center justify-center">
             {loopedModels.map((model, index) => (
                <ScrollModel 
                  key={`${model.id}-${index}`}
                  model={model}
                  index={index}
                  total={loopedModels.length}
                  progress={smoothProgress}
                />
             ))}
          </div>
        </div>

        {/* RIGHT: Synchronized Scrollable Column. Each card matches a giant model! */}
        <div className="w-[35%] lg:w-[30%] bg-white border-l border-black/5 relative z-30 shadow-[-10px_0_30px_rgba(0,0,0,0.03)]">
           <div className="flex flex-col">
             {loopedModels.map((listModel, index) => (
                <div key={`sidebar-${listModel.id}-${index}`} className="min-h-screen p-12 border-b border-black/5 flex flex-col justify-center items-center group">
                  <div className="relative w-[75%] aspect-[3/4] mb-8 overflow-hidden rounded-sm bg-[#fafafa] flex items-center justify-center pt-8">
                    <div className="relative w-[90%] h-[90%]">
                        <Image 
                        src={listModel.src}
                        alt={listModel.title}
                        fill
                        className="object-contain drop-shadow-xl group-hover:scale-105 transition-transform duration-700"
                        />
                    </div>
                  </div>
                  <div className="w-full text-center flex flex-col items-center">
                    <h4 className="text-sm font-bold uppercase tracking-widest mb-3">{listModel.title}</h4>
                    <p className="text-[11px] font-medium text-black/50 leading-relaxed mb-4 px-4 max-w-[90%]">{listModel.desc}</p>
                    <p className="text-sm font-semibold tracking-wider mb-6">{listModel.price}</p>
                    
                    <button className="px-10 py-3 bg-black text-white text-[10px] font-bold uppercase tracking-[0.2em] hover:bg-black/80 transition-colors rounded-sm">
                      Shop The Look
                    </button>
                  </div>
               </div>
             ))}
             {/* Small padding block so the very last model can be fully scrolled into view beautifully */}
             <div className="h-[30vh] bg-white"></div>
           </div>
        </div>

      </div>
    </main>
  );
}

function ScrollModel({ model, index, total, progress }: any) {
  // Matches the timeline directly to the vertical scrolling items 
  const activeFloat = useTransform(progress, [0, 1], [0, total - 0.7]);
  
  const relativePosRaw = useTransform(activeFloat, v => index - v);
  const relativePos = useTransform(relativePosRaw, v => Math.max(-1.5, Math.min(v, 4)));

  // X offset: 
  // v = 0 (Main): x = 180 (Right biased)
  // v = 1 (Next): x = -280 (Left queue)
  // v = -1 (Passed): x = 600 (Exits far right)
  const x = useTransform(relativePos, [-1, 0, 1, 2, 3], [600, 180, -280, -550, -750], { clamp: true });
  
  // Scaling: 1.0 at center, descending as it goes back into the queue (v > 0)
  const scale = useTransform(relativePos, [-1, 0, 1, 2, 3], [1.1, 1.0, 0.65, 0.45, 0.3], { clamp: true });
  
  // Opacity & Blur: Descending into the queue
  const opacity = useTransform(relativePos, [-1, -0.5, 0, 1, 2, 3], [0, 0.8, 1, 0.5, 0.15, 0], { clamp: true });
  const blurVal = useTransform(relativePos, [-1, 0, 1, 2, 3], [0, 0, 6, 12, 18], { clamp: true });
  const filter = useMotionTemplate`blur(${blurVal}px)`;
  
  return (
    <motion.div 
      style={{ x, scale, opacity, filter, zIndex: 50 - index }}
      className="absolute top-0 bottom-0 left-0 right-0 flex items-center justify-center pointer-events-none"
    >
      <div className="relative w-full h-[85vh] max-w-[80vw]">
        <Image src={model.src} alt={model.title} fill className="object-contain" priority={index < 2} />
      </div>
    </motion.div>
  );
}
